name: Check PR reviewers
on:
  pull_request_review:

jobs:
  review:
    name: Require team reviews
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get team members
        id: get-team-members
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.TEAM_REVIEW_TOKEN }}
          script: |
            const getTeamMembers = require('./.github/scripts/get-team-members')
            return await getTeamMembers({
              github,
              context,
              teams: [
                'futurenow',
                'futurenow-design',
                'futurenow-qa'
              ]
            })
      - name: Ensure each team reviews
        uses: actions/github-script@v6
        with:
          script: |
            const review = require('./.github/scripts/team-review')
            await review({
              github,
              context,
              core,
              teams: ${{ steps.get-team-members.outputs.result }}
            })
