name: CI
on:
  workflow_dispatch:
    inputs:
      environment:
        description: Job to dispatch
        required: true
        type: choice
        options:
          - node
          - lint
          - test
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      print_tags:
        description: 'True to print to STDOUT'
        required: true
        type: boolean
      tags:
        description: 'Test scenario tags'
        required: false
        type: string
        
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
  PR_PATH: /pr/${{ github.event.pull_request.number }}

jobs:
  lint:
    if: |
      github.event_name != 'pull_request' ||
      # github.event.action != 'closed' ||
      # github.event.pull_request.merged == true ||
      github.event.inputs.environment == 'lint' ||
      github.event.inputs.environment == 'node'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'npm'
      - run: npm ci
      - name: Run linter
        run: npm run lint

  test:
    if: |
      github.event_name != 'pull_request' ||
      github.event.action != 'closed' ||
      github.event.pull_request.merged == true
      github.event.inputs.environment == 'test'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ''
          cache: 'npm'
      - run: npm ci
      - name: Run tests
        run: npm run test
        
